spring:
  application:
    name: validation-flow-engine

management:
  endpoint:
    health:
      probes:
        enabled: true

logging:
  pattern:
    level: "%5p [%X{correlationId:-},%X{executionId:-},%X{flowKey:-},%X{flowVersion:-},%X{nodeId:-},%X{status:-}]"
